spring:
    jpa:
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        hibernate:
            ddl-auto: validate
        open-in-view: false
    datasource:
        url: jdbc:sqlite:openai-queries.db
        driver-class-name: org.sqlite.JDBC

forward:
    url: https://api.openai.com/v1/chat/completions
